# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(903, 539)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        Form.setFont(font)
        Form.setStyleSheet("#Form{\n"
"    background-color:black;\n"
"}")
        self.webcam_box = QtWidgets.QComboBox(Form)
        self.webcam_box.setGeometry(QtCore.QRect(510, 400, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.webcam_box.setFont(font)
        self.webcam_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.webcam_box.setStyleSheet("background-color:black;\n"
"border:1px solid gray;\n"
"border-radius:15px;\n"
"color:white;")
        self.webcam_box.setObjectName("webcam_box")
        self.webcam_box.addItem("")
        self.webcam_box.addItem("")
        self.qr_frame = QtWidgets.QLabel(Form)
        self.qr_frame.setGeometry(QtCore.QRect(480, 90, 281, 281))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.qr_frame.setFont(font)
        self.qr_frame.setStyleSheet("background-color: transparent;\n"
"border:1px solid transparent;\n"
"border-radius:30px;\n"
"color: rgb(206, 206, 206);")
        self.qr_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_frame.setObjectName("qr_frame")
        self.connect_qr = QtWidgets.QPushButton(Form)
        self.connect_qr.setGeometry(QtCore.QRect(510, 450, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.connect_qr.setFont(font)
        self.connect_qr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connect_qr.setStyleSheet("QPushButton{\n"
"    color:gray;\n"
"    background-color:black;\n"
"    border:1px solid green;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    background-color:black;\n"
"    \n"
"    border-color: rgb(115, 255, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color:green;\n"
"    background-color:black;\n"
"}")
        self.connect_qr.setObjectName("connect_qr")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 140, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(206, 206, 206);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ssid_input = QtWidgets.QLineEdit(Form)
        self.ssid_input.setGeometry(QtCore.QRect(140, 170, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ssid_input.setFont(font)
        self.ssid_input.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"    background-color:black;\n"
"    \n"
"    border: 1px solid white;\n"
"    border-radius:15px;\n"
"}")
        self.ssid_input.setText("")
        self.ssid_input.setAlignment(QtCore.Qt.AlignCenter)
        self.ssid_input.setObjectName("ssid_input")
        self.manually_btn = QtWidgets.QPushButton(Form)
        self.manually_btn.setGeometry(QtCore.QRect(140, 290, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.manually_btn.setFont(font)
        self.manually_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manually_btn.setStyleSheet("QPushButton{\n"
"    color:rgb(200,255,255);\n"
"    background-color:black;\n"
"    border:1px solid green;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:black;\n"
"    border-color: rgb(200, 255, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color:green;\n"
"    background-color:black;\n"
"    border-color:greenl\n"
"}")
        self.manually_btn.setObjectName("manually_btn")
        self.pass_input = QtWidgets.QLineEdit(Form)
        self.pass_input.setGeometry(QtCore.QRect(140, 240, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pass_input.setFont(font)
        self.pass_input.setStyleSheet("QLineEdit{\n"
"    color:white;\n"
"    background-color:black;\n"
"    border:1px solid white;\n"
"    border-radius:15px;\n"
"}")
        self.pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_input.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_input.setObjectName("pass_input")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(140, 210, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(206, 206, 206);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.remove_btn = QtWidgets.QPushButton(Form)
        self.remove_btn.setGeometry(QtCore.QRect(140, 340, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.remove_btn.setFont(font)
        self.remove_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_btn.setStyleSheet("QPushButton{\n"
"    color:gray;\n"
"    background-color:black;\n"
"    border:1px solid rgb(200,0,0);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    background-color:black;\n"
"    \n"
"    border-color: red;\n"
"}\n"
"QPushButton:pressed{\n"
"    color:red;\n"
"    background-color:black;\n"
"}")
        self.remove_btn.setObjectName("remove_btn")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(480, 90, 61, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(480, 90, 3, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(701, 370, 61, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(760, 311, 3, 61))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(760, 90, 3, 61))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(700, 90, 61, 3))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(480, 310, 3, 61))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(480, 370, 61, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_4.raise_()
        self.webcam_box.raise_()
        self.qr_frame.raise_()
        self.connect_qr.raise_()
        self.label.raise_()
        self.ssid_input.raise_()
        self.manually_btn.raise_()
        self.pass_input.raise_()
        self.label_3.raise_()
        self.remove_btn.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.webcam_box.setItemText(0, _translate("Form", "  Default laptop camera"))
        self.webcam_box.setItemText(1, _translate("Form", "  Additional webcam"))
        self.qr_frame.setText(_translate("Form", "The camera is closed!"))
        self.connect_qr.setText(_translate("Form", "Connect with QR"))
        self.label.setText(_translate("Form", "SSID"))
        self.manually_btn.setText(_translate("Form", "Connect manually"))
        self.label_3.setText(_translate("Form", "Password"))
        self.remove_btn.setText(_translate("Form", "Remove all profiles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
